### PR TITLE
Raise 400 error if repo is not specified for sync/publish

### PR DESCRIPTION
**Pull request by daviddavis**
fixes #3384
https://pulp.plan.io/issues/3384

### CODE REVIEW

**Comment by dkliban** [comment]
ok test

**Comment by daviddavis** [comment]
ok test

**Comment by daviddavis** [comment]
ok test

**Comment by daviddavis** [comment]
ok test

**Comment by daviddavis** [comment]
ok test

**Comment by daviddavis** [comment]
ok test

**Comment by daviddavis** [comment]
Closing in favor of https://github.com/pulp/pulp_file/pull/47

**Pull request closed without merging**
