### PR TITLE
Add a Header ContentGuard test.

### PR DESCRIPTION
**Pull request by decko**
[noissue]

### CODE REVIEW

**Comment by decko** [comment]
> Why can't we add this test to the repository bringing the content guard?

The repository containing the content guard have unittests for it.
For functional tests we're only able to add it here given the components needed to run setup the tests.

**Comment by mdellweg** [comment]
> > Why can't we add this test to the repository bringing the content guard?
> 
> The repository containing the content guard have unittests for it. For functional tests we're only able to add it here given the components needed to run setup the tests.

What components? pulp_file (released) is a test requirement for pulpcore what else is missing?

**Comment by decko** [comment]
> > > Why can't we add this test to the repository bringing the content guard?
> > 
> > 
> > The repository containing the content guard have unittests for it. For functional tests we're only able to add it here given the components needed to run setup the tests.
> 
> What components? pulp_file (released) is a test requirement for pulpcore what else is missing?
> 
> There was a time when we had a rule that pulpcore tests must not rely on pulp_file, but that was when we tested main branches against each other. This is no longer true.

Wow! Thanks man. Shame on me, I didn't know that.
I've moved this test to `pulpcore` repo, where it belongs.

Thanks again @mdellweg

**Comment by decko** [comment]
Closing given we found a better place to this piece of code.

**Pull request closed without merging**
