### PR TITLE
Expand duplicate content unit test case

### PR DESCRIPTION
**Pull request by kersommoura**
Expand newly added duplicate content unit test case. Add a test case to
confirm that content units using the same artifact, but different
relative_paths can be create without raise an HTTP exception.

https://pulp.plan.io/issues/4125
ref: #4125

### CODE REVIEW

**Comment by kersommoura** [comment]
ping @pulp/qe 

I added an extra test case to cover the negative case.

@daviddavis, please, can you review/merge this one?

**Comment by dralley** [comment]
@kersommoura @daviddavis Should this test case be something we duplicate for each plugin, or would it be sufficient to have one copy of this and move it to pulpcore/tests/functional/using_plugin?

**Comment by kersommoura** [comment]
@dralley , after finishing this test here. I intend to add to the: pulp_docker, pulp_rpm, and pulp_template. 
If there is a different understanding I can move the test as well.

**Comment by daviddavis** [comment]
@dralley I think this test is going to be specific to each plugin. [The error message will be different](https://github.com/pulp/pulp_file/blob/master/pulp_file/app/serializers.py#L37-L40) and it sounds like some Content might not even have natural keys.

**Comment by kersommoura** [comment]
I rebased this PR again.

@dralley, please, can you merge it?

**Comment by daviddavis** [comment]
Done. Thanks :+1:

**Pull request merged**
