### PR TITLE
Add demo requirement to docs

### PR DESCRIPTION
**Pull request by melcorr**
fixes #7704

I added the requirement to record a demo from the Pulpcore docs. 

I noticed that the file structures are different in this repo, so I just followed the example here, if that is OK. 

Happy to change anything you want.

### CODE REVIEW

**Comment by daviddavis** [comment]
Is the plan to roll this out to every plugin? What if we linked to [the demo docs in pulpcore](https://docs.pulpproject.org/pulpcore/en/master/nightly/contributing/record-a-demo.html) instead?

**Comment by daviddavis** [comment]
@melcorr ping.

**Comment by melcorr** [comment]
> @melcorr ping.

I just swap everything out and add a link?

**Comment by melcorr** [comment]
Sorry for the delay. The first 13 days of 2021 sure were long. 
Thanks for your patience.

**Review by daviddavis — APPROVED** [review]

**Comment by daviddavis** [comment]
No problem on the delay. 

Looks like you need a `CHANGES/7704.doc` here.

**Comment by melcorr** [comment]
> No problem on the delay.
> 
> Looks like you need a `CHANGES/7704.doc` here.

Will add that now.

**Pull request merged**
