### PR TITLE
Validates that repository has a version to publish

### PR DESCRIPTION
**Pull request by dralley**
Raise a ValidationError if you try to publish a repository which
does not have any versions.

closes #3583
https://pulp.plan.io/issues/3583

### CODE REVIEW

**Comment by daviddavis** [comment]
Since this is validation, what about moving this into the serializer?

**Comment by dralley** [comment]
We could do it this way.  Is there a way to, inside the serializer, just set the "repository_version" and the only use that?

**Comment by dralley** [comment]
Is there a way to, inside the serializer, just set the "repository_version" and the only use that?  That would be ideal.

**Comment by dralley** [comment]
@daviddavis please re-review

**Comment by daviddavis** [comment]
Works great. Thanks @dralley.

**Pull request merged**
