### PR TITLE
Add a functional test to the checklist for contributors

### PR DESCRIPTION
**Pull request by goosemania**
closes #7437
https://pulp.plan.io/issues/7437

### CODE REVIEW

**Comment by ipanova** [comment]
do we want to enforce it in Travis?

**Comment by daviddavis** [comment]
@ipanova I think it's worth considering. Maybe add it as a topic to our next pulpcore meeting agenda?

**Comment by ipanova** [comment]
> @ipanova I think it's worth considering. Maybe add it as a topic to our next pulpcore meeting agenda?

will do. there is an opened PR for pulp_rpm that enforces tests, we can just copy over some of the changes once they get approved.

**Comment by goosemania** [comment]
@ipanova , @daviddavis , should this PR wait for a decision? Or will it be a separate PR? basically, merge or wait?

**Comment by ipanova** [comment]
I would merge and adress the rest in another pr.

**Comment by goosemania** [comment]
Travis is green just for whatever reason is not reporting it back. Merging.

**Pull request merged**
