### PR TITLE
Fixed 0012_delete_filefilesystemexporter migration

### PR DESCRIPTION
**Pull request by daviddavis**
fixes #9102

### CODE REVIEW

**Comment by daviddavis** [comment]
I only know of this fix because of the distribution migration (see below) and I am not totally sure why it works.

https://github.com/pulp/pulp_file/blob/d0dd4ebd6f2c960db3441d572ba6f825210f0e03/pulp_file/app/migrations/0009_move_data_to_new_master_distribution_model.py#L48

**Comment by dralley** [comment]
Adding @mdellweg as a reviewer since he wrote the original patch

**Comment by mdellweg** [comment]
I only have a theory:
In this other migration, a table got renamed. And at the end of the transaction, some triggers were pending on the old table (-name) and failed. Setting `atomic=False` end the transactions earlier, and thereby triggers triggers earlier.

**Review by mdellweg — APPROVED** [review]
Here the deleting of objects will probably add some triggers on the table that is removed in the next step.
The only other solution might be to split the migration in two.

**Pull request merged**
